min_valid_kf_count_threshold: 25
iteration_start_threshold: 50
target_publish_frequency_hz: 10.0 # Hz

vtol_payload: True
zed_baseline: 0.12 # meters

linear_velocity_dropout: 2.0 # meters / second
angular_velocity_dropout: 1.0 # radians / second

initial_covariance_multiplier: 3.0 # multiplier for initial yaw covariance
wire_matching_min_threshold_m: 0.15 # meters
valid_count_buffer: 3

yaw_predict_covariance: 0.01 # radians
yaw_measurement_covariance: 0.10 # radians
yaw_max_covariance: 0.10 # radians

z_predict_covariance: 0.03 # meters
z_measurement_covariance: 0.30 # meters
z_max_covariance: 0.30 # meters

y_predict_covariance: 0.02 # meters
y_measurement_covariance: 0.20 # meters
y_max_covariance: 0.20 # meters
