#Wire Detection Settings
# hough_vote_threshold: 150
# min_line_threshold: 200
hough_vote_threshold: 50
min_line_threshold: 80
pixel_binning_size: 5
low_canny_threshold: 25
high_canny_threshold: 150
line_bin_avg_threshold_multiplier: 0.35

# ROI settings
grad_bin_avg_threshold: 0.7
max_wire_per_roi: 3
min_depth_clip_m: 0.5
max_depth_clip_m: 1.75

# RANSAC settings
ransac_max_iters: 750
inlier_threshold_m: 0.1016 # 4 inches
vert_angle_maximum_rad: 0.174533 # 10 degrees
horz_angle_diff_maximum_rad: 0.0698132 # 4 degrees
