services:
  base:
    image: tharp789/hummingbird_demo:base-${L4T_MAJOR}-${L4T_MINOR}-${L4T_PATCH}
    build:
      context: ./
      dockerfile: docker/Dockerfile.base
      args:
        L4T_MAJOR: ${L4T_MAJOR}
        L4T_MINOR: ${L4T_MINOR}
        L4T_PATCH: ${L4T_PATCH}
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NDDS_QOS_PROFILE=/root/rti_sensor_qos_profile.xml
    network_mode: host
    runtime: nvidia
    privileged: true
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 0

  rtsp:
    image: tharp789/hummingbird_demo:rtsp-${L4T_MAJOR}-${L4T_MINOR}-${L4T_PATCH} 
    build:
      context: ./
      dockerfile: docker/Dockerfile.rtsp
      args:
        BASE_IMAGE: tharp789/hummingbird_demo:base-${L4T_MAJOR}-${L4T_MINOR}-${L4T_PATCH}
    depends_on:
    - base
    entrypoint: ["/root/entrypoint.sh"]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NDDS_QOS_PROFILE=/root/rti_sensor_qos_profile.xml
    network_mode: host
    runtime: nvidia
    privileged: true
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    volumes:
      - /tmp:/tmp 
      - /dev:/dev 
      - ./rti_sensor_qos_profile.xml:/root/rti_sensor_qos_profile.xml 
      - ./image2rtsp/:/root/ros2_ws/src/:rw

  zed_wrapper:
    image: tharp789/hummingbird_demo:zed-wrapper-${L4T_MAJOR}-${L4T_MINOR}-${L4T_PATCH} 
    build: 
      context: ./
      dockerfile: docker/Dockerfile.zed
      args:
        BASE_IMAGE: tharp789/hummingbird_demo:base-${L4T_MAJOR}-${L4T_MINOR}-${L4T_PATCH}
    depends_on:
    - base
    entrypoint: ["/root/entrypoint.sh"]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NDDS_QOS_PROFILE=/root/rti_sensor_qos_profile.xml
      - POSE_CAM_SERIAL=${POSE_CAM_SERIAL}
      - WIRE_CAM_SERIAL=${WIRE_CAM_SERIAL}
    network_mode: host
    runtime: nvidia
    privileged: true
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    volumes:
      - /tmp:/tmp 
      - /dev:/dev 
      - ./rti_sensor_qos_profile.xml:/root/rti_sensor_qos_profile.xml 
      - /var/nvidia/nvcam/settings/:/var/nvidia/nvcam/settings/
      - /etc/systemd/system/zed_x_daemon.service:/etc/systemd/system/zed_x_daemon.service
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /usr/local/zed/settings/:/usr/local/zed/settings/
      - ./zed_wrapper/:/root/ros2_ws/src/:rw
  
  autonomy:
    image: tharp789/hummingbird_demo:autonomy-${L4T_MAJOR}-${L4T_MINOR}-${L4T_PATCH} 
    build:
      context: ./ 
      dockerfile: docker/Dockerfile.autonomy
      args:
        BASE_IMAGE: tharp789/hummingbird_demo:base-${L4T_MAJOR}-${L4T_MINOR}-${L4T_PATCH}
    depends_on:
    - base
    entrypoint: ["/root/entrypoint.sh"]
    stop_signal: SIGINT
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NDDS_QOS_PROFILE=/root/rti_sensor_qos_profile.xml
      - WIRE_MODE=${WIRE_MODE}
      - WIRE_VIZ=${WIRE_VIZ}
      - RECORD=${RECORD}
      - RVIZ=${RVIZ}
      - VO=${VO}
      - SERVO=${SERVO}
      - MAVROS=${MAVROS}
      - SIMULATION=${SIMULATION}
    deploy:
      # let it use the GPU
      resources:
        reservations:
          devices:
            - driver: nvidia # https://stackoverflow.com/a/70761193
              count: 1
              capabilities: [ gpu ]
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    runtime: nvidia
    privileged: true
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    volumes:
      - /tmp:/tmp 
      - /dev:/dev 
      - ./rti_sensor_qos_profile.xml:/root/rti_sensor_qos_profile.xml 
      - ./autonomy/:/root/ros2_ws/:rw
      - ${STORAGE_PATH}:/root/data_collection/:rw

networks:
  hummingbird_network:
    driver: bridge
    attachable: true
