services:
  rtsp:
    image: rtsp-ros2
    build:
      context: ./
      dockerfile: docker/Dockerfile.rtsp
    command: >
      bash -c "source /opt/ros/humble/install/setup.bash && \
               source /root/ros2_ws/install/local_setup.bash && \
               ros2 launch image2rtsp image2rtsp.launch.py && sleep infinity"
  zed_wrapper:
    image: zed-wrapper-ros2  
    build: 
      context: ./
      dockerfile: docker/Dockerfile.zed-dev
    command: >
      bash -c "source /opt/ros/humble/install/setup.bash && \
               source /root/ros2_ws/install/local_setup.bash && \
               ros2 launch zed_wrapper zed_camera.launch.py camera_model:='zedx' && sleep infinity"
    runtime: nvidia
    privileged: true
    ipc: host
    pid: host
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
    stdin_open: true  # Equivalent to -it for interactive terminal
    tty: true  # Ensures that a pseudo-terminal is allocated
    volumes:
      - /dev:/dev 
      - /tmp:/tmp 
      - /var/nvidia/nvcam/settings/:/var/nvidia/nvcam/settings/
      - /etc/systemd/system/zed_x_daemon.service:/etc/systemd/system/zed_x_daemon.service
      - ${HOME}/zed_docker_ai/:/usr/local/zed/resources/
  autonomy:
    image: autonomy-ros2
    build:
      context: ./ 
      dockerfile: docker/Dockerfile.autonomy
    command: >
      bash -c "colcon build && \
               source /opt/ros/humble/install/setup.bash && \
               source /root/ros2_ws/install/local_setup.bash && \
               sleep infinity"
    volumes:
      - ./autonomy/:/root/ros2_ws/:rw
      - /media/airlab/T7/wire_detection_bags/:/root/storage:rw
