/**:
  ros__parameters:
    camera_info_sub_topic: "/wire_cam/zed_node/left/camera_info"
    imageL_sub_topic: "left/image_rect"
    imageR_sub_topic: "right/image_rect"
    pose_pub_topic: "visual_odometry_pose"
    point_pub_topic: "visual_odometry_points"
    img_pub_topic: "visual_odometry_img"
    inference_dim_u: 450
    inference_dim_v: 350
    baseline: 0.12
