/**:
  ros__parameters:

    # subscribers
    camera_info_sub_topic: "/wire_cam/zed_node/left/camera_info"
    rgb_image_sub_topic: "/wire_cam/zed_node/left/image_rect_color"
    depth_image_sub_topic: "/wire_cam/zed_node/depth/depth_registered"
    use_pose_cam: true
    pose_sub_topic: ""

    # publishers
    wire_viz_pub_topic: "/wire_cam/detection_debug"
    depth_viz_pub_topic: "/wire_cam/depth_debug"
    pose_viz_pub_topic: "/wire_cam/pos_debug"
    seg_mask_pub_topic: "/wire_cam/seg_mask"
    depth_pc_pub_topic: "/wire_cam/depth_pointcloud"
    wire_estimator_pub_topic: "/wire_cam/wire_estimation"\

    # general settings
    use_gpu: false
    vizualize: true
