/**:
  ros__parameters:

    # subscribers
    camera_info_sub_topic: "/wire_cam/zed_node/left/camera_info"
    rgb_image_sub_topic: "/wire_cam/zed_node/left/image_rect_color"
    depth_image_sub_topic: "/wire_cam/zed_node/depth/depth_registered"
    pose_sub_topic: "/vins/camera_pose"


    # internode publishers
    wire_detections_pub_topic: "/pincer/wire_detections"
    wire_target_pub_topic: "/pincer/wire_target"
    velocity_pub_topic: "/mavros/setpoint_velocity/cmd_vel"

    # viz publishers
    depth_viz_pub_topic: "/pincer/viz_depth"
    pose_viz_pub_topic: "/pincer/viz_pose"
    depth_pc_pub_topic: "/pincer/depth_pc_viz"

    detections_2d_pub_topic: "/pincer/viz_detections_2d"
    detections_3d_pub_topic: "/pincer/viz_detections_3d"

    tracking_2d_pub_topic: "/pincer/viz_tracking_2d"
    tracking_3d_pub_topic: "/pincer/viz_tracking_3d"

    # general settings
    use_cpu: true
    vizualize_wires: true
