/**:
  ros__parameters:

    # subscribers
    camera_info_sub_topic: "/wire_cam/zed_node/left/camera_info"
    rgb_image_sub_topic: "/wire_cam/zed_node/left/image_rect_color"
    depth_image_sub_topic: "/wire_cam/zed_node/depth/depth_registered"
    pose_sub_topic: "/vins/camera_pose"

    # internode publishers
    wire_detections_topic: "/pincer/wire_detections"
    wire_target_topic: "/pincer/wire_target"
    velocity_cmd_topic: "/mavros/setpoint_raw/local"

    # viz publishers
    depth_viz_topic: "/pincer/depth_viz"
    pose_viz_topic: "/pincer/pose_viz"
    depth_pc_topic: "/pincer/depth_pc_viz"

    detections_2d_viz_topic: "/pincer/detections_2d_viz"
    detections_3d_viz_topic: "/pincer/detections_3d_viz"

    tracking_2d_viz_topic: "/pincer/tracking_2d_viz"
    tracking_3d_viz_topic: "/pincer/tracking_3d_viz"

    # general settings
    use_cpu: true
    use_mask: true