/**:
  ros__parameters:
    
    # subscribers
    camera_info_sub_topic: "/wire_cam/zed_node/left/camera_info"
    rgb_image_sub_topic: "/wire_cam/zed_node/left/image_rect_color"
    depth_image_sub_topic: "/wire_cam/zed_node/depth/depth_registered"
    use_pose_cam: true
    pose_sub_topic: ""

    # publishers
    wire_viz_pub_topic: "/wire_cam/detection_debug"
    depth_viz_pub_topic: "/wire_cam/depth_debug"
    pose_viz_pub_topic: "/wire_cam/pos_debug"
    seg_mask_pub_topic: "/wire_cam/seg_mask"
    depth_pc_pub_topic: "/wire_cam/depth_pointcloud"
    wire_estimator_pub_topic: "/wire_cam/wire_estimation"

    # Wire detection params
    # ROI settings
    grad_bin_avg_threshold: 0.05
    max_wire_per_roi: 3
    min_depth_clip_m: 0.5
    max_depth_clip_m: 12.0
    # RANSAC settings
    ransac_max_iters: 300
    inlier_threshold_m: 0.1016 # 4 inches
    vert_angle_maximum_rad: 0.174533 # 10 degrees
    horz_angle_diff_maximum_rad: 0.0698132 # 4 degrees

    # KF params
    max_distance_threshold: 0.15 # meters
    min_valid_kf_count_threshold: 15
    iteration_start_threshold: 0
    # yaw_covariance: 0.0349066 # radians
    yaw_covariance: 0.05 # radians
    pos_covariance: 0.20 # meters
