y_wire_offset_from_camera_m: 0.0
z_wire_offset_from_camera_m: 0.0

kp_xy_value: 0.0
kd_xy_value: 0.0
ki_xy_value: 0.0
v_xy_limit: 0.0

kp_z_value: 0.0
kd_z_value: 0.0
ki_z_value: 0.0
v_z_limit: 0.0

kp_yaw_value: 0.0
kd_yaw_value: 0.0
ki_yaw_value: 0.0
v_yaw_limit: 0.0


    
