takeoff_height: 2.0 # m
takeoff_wait_time: 10.0 # s
target_timeout: 0.25
velocity_command_frequency: 15.0 # Hz

x_wire_offset_from_camera_m: 0.5
z_wire_offset_from_camera_m: 1.0
yaw_wire_offset_from_camera_rad: 1.5708

kp_xy: 0.25
kd_xy: 0.1
ki_xy: 0.0
v_xy_limit: 0.5

kp_z: 0.125
kd_z: 0.05
ki_z: 0.0
v_z_limit: 0.25

kp_yaw: 0.25
kd_yaw: 0.2
ki_yaw: 0.0
v_yaw_limit: 0.17
    
