services:
  ardupilot_sitl:
    image: tharp789/ardupilot_sitl:humble_ardupilot_sitl
    ports:
      - "5760:5760/tcp"
    build:
      context: ./ 
      dockerfile: ./Dockerfile.sitl
    entrypoint: ["/root/entrypoint.sh"]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    network_mode: host
    privileged: true
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    volumes:
      - /tmp:/tmp 
      - /dev:/dev 
      - ./iris:/root/ardu_ws/src/ardupilot_gazebo/models/iris_with_standoffs
      - ./params:/root/ardu_ws/src/ardupilot_gazebo/config
      - ./worlds:/root/ardu_ws/src/ardupilot_gz/ardupilot_gz_gazebo/worlds

networks:
  sitl_network:
    driver: bridge
    attachable: true
