# Any line that does not start with a / will be automatically prefixed using the 
# any line ending in / will be treated as a prefix for all topics that start with that prefix.
# namespace of the bag_recorder node.
# mcap_qos is the filename of the MCAP QoS profile. The actual directory will be prefixed by the
# bag_recorder node via a user specified argument. All MCAP QoS files must be in the same directory.

sections:
  wire_tracking:
    mcap_qos: mcap_qos.yaml
    args: 
      - -d
      - 60 # ~1min
      - --max-cache-size 
      - 1073741824 # 1GB
    topics:
      - /parameter_events
      - /rosout
      - /wire_cam/zed_node/left/image_rect_color
      - /wire_cam/zed_node/right/image_rect_color
      - /wire_cam/zed_node/left/camera_info
      - /wire_cam/zed_node/right/camera_info
      - /wire_cam/zed_node/depth/depth_registered
      - /pose_cam/zed_node/left/image_rect_color
      - /pose_cam/zed_node/right/image_rect_color
      - /pose_cam/zed_node/left/camera_info
      - /pose_cam/zed_node/right/camera_info
      - /mavros/setpoint_raw/local
      - /mavros/setpoint_raw/global
      - /mavros/setpoint_raw/attitude
      - /mavros/global_position/global
      - /mavros/global_position/local
      - /mavros/global_position/gp_vel
      - /mavros/global_position/rel_alt
      - /mavros/global_position/compass_hdg
      - /mavros/global_position/raw/satellites
      - /mavros/global_position/raw/fix
      - /mavros/global_position/raw/gps_vel
      - /mavros/local_position/accel
      - /mavros/local_position/odom
      - /mavros/local_position/pose
      - /mavros/local_position/pose_cov
      - /mavros/local_position/velocity_body
      - /mavros/local_position/velocity_body_cov
      - /mavros/local_position/velocity_local
      - /mavros/home_position/home
      - /mavros/imu/data
      - /mavros/imu/data_raw
      - /mavros/imu/mag
      - /mavros/imu/temperature
      - /mavros/imu/atm_pressure
      - /mavros/local_position/pose
      - /mavros/local_position/velocity
      - /mavros/manual_control/control
      - /mavros/odometry/out
      - /mavros/rc/in
      - /mavros/rc/out
      - /mavros/state
      - /mavros/param/event
      - /mavros/vfr_hud
      - /mavros/wind_estimation
      - /mavros/battery
      - /diagnostics
      - /mavlink/from
      - /mavlink/to
      - /mavros/trajectory/desired
      - /mavros/trajectory/generated
      - /mavros/trajectory/path
      - /mavros/sys_status

