# Any line that does not start with a / will be automatically prefixed using the 
# any line ending in / will be treated as a prefix for all topics that start with that prefix.
# namespace of the bag_recorder node.
# mcap_qos is the filename of the MCAP QoS profile. The actual directory will be prefixed by the
# bag_recorder node via a user specified argument. All MCAP QoS files must be in the same directory.

sections:
  pincer:
    mcap_qos: mcap_qos.yaml
    args: 
      - -d
      - 60 # ~1min
      - --max-cache-size 
      - 1073741824 # 1GB
    topics:
      - /parameter_events
      - /rosout
      - /wire_cam/zed_node/left/image_rect_color
      - /wire_cam/zed_node/right/image_rect_color
      - /wire_cam/zed_node/left/camera_info
      - /wire_cam/zed_node/right/camera_info
      - /wire_cam/zed_node/depth/depth_registered
      - /pose_cam/zed_node/left/image_rect_color
      - /pose_cam/zed_node/right/image_rect_color
      - /pose_cam/zed_node/left/camera_info
      - /pose_cam/zed_node/right/camera_info
      - /mavros/
