%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1032
image_height: 772
distortion_parameters:
   k1: -0.197412
   k2: 0.236726
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 868.246
   fy: 868.246
   cx: 516.0
   cy: 386.0

