/**:
  ros__parameters:
    
    # subscribers
    camera_info_sub_topic: "/wire_cam/zed_node/left/camera_info"
    rgb_image_sub_topic: "/wire_cam/zed_node/left/image_rect_color"
    depth_image_sub_topic: "/wire_cam/zed_node/depth/depth_registered"
    pose_sub_topic: "/pose_cam/zed_node/pose"

    # publishers
    wire_viz_pub_topic: "/wire_cam/detection_debug"
    depth_viz_pub_topic: "/wire_cam/depth_debug"
    pos_viz_pub_topic: "/wire_cam/pos_debug"

    # Wire detection params
    expansion_size: 10
    point_threshold: 350

    # KF params
    max_distance_threshold: 0.25 # meters
    min_valid_kf_count_threshold: 20
    iteration_start_threshold: 30
