/**:
  ros__parameters:
    
    # subscribers
    camera_info_sub_topic: "/wire_cam/zed_node/left/camera_info"
    rgb_image_sub_topic: "/wire_cam/zed_node/left/image_rect_color"
    depth_image_sub_topic: "/wire_cam/zed_node/depth/depth_registered"
    use_pose_cam: true
    pose_sub_topic: "/zed_node/pose"

    # publishers
    wire_viz_pub_topic: "/wire_cam/detection_debug"
    depth_viz_pub_topic: "/wire_cam/depth_debug"
    pose_viz_pub_topic: "/wire_cam/pos_debug"
    seg_mask_pub_topic: "/wire_cam/seg_mask"

    # Wire detection params
    expansion_size: 10
    line_threshold: 250

    # KF params
    max_distance_threshold: 0.15 # meters
    min_valid_kf_count_threshold: 15
    iteration_start_threshold: 0
    # yaw_covariance: 0.0349066 # radians
    yaw_covariance: 0.05 # radians
    pos_covariance: 0.20 # meters
